/**
 * Maps route pathname to backend module name (as in Roles & Permissions).
 * Used to check canView/canCreate/canUpdate/canDelete for the current user's role.
 */
export const ROUTE_TO_MODULE_NAME: Record<string, string> = {
  "/dashboard": "Dashboard",
  "/patients": "Patients",
  "/claims": "Claims",
  "/settings": "Settings & Configurations",
  "/settings/organization": "Organizations",
  "/settings/users": "Users",
  "/settings/roles-permissions": "Roles",
  "/settings/security-access": "Security Access",
  "/settings/entities": "Entities",
  "/settings/entity-locations": "Entity Locations",
  "/settings/entity-providers": "Entity Providers",
  "/settings/entity-fee-schedules": "Entity Fee Schedules",
  "/settings/payers": "Payers",
  "/settings/plans": "Plans",
  "/settings/group-participation": "Group Provider Plan Participations",
  "/settings/rendering-participation": "Rendering Provider Plan Participations",
  "/settings/facilities": "Facilities",
  "/settings/fee-schedules": "Fee Schedules",
  "/settings/geography-resolution": "Zip Geo Mappings",
  "/settings/applicability-rules": "Applicability Rules",
  "/settings/icd-codes": "ICD Codes",
  "/settings/ndc-codes": "NDC Codes",
  "/settings/cpt-hcpcs-codes": "CPT/HCPCS Codes",
  "/settings/modifiers": "Modifiers",
  "/settings/financial-modifiers": "Financial Modifiers",
  "/settings/bundling-reduction-rules": "Bundling/Reduction Rules",
  "/settings/procedure-grouping-rules": "Procedure Grouping Rules",
  "/settings/nsa-eligibility": "NSA Eligibility",
  "/settings/nsa-federal": "NSA Federal",
  "/settings/nsa-state": "NSA State",
  "/settings/nsa-emergency": "NSA Emergency",
  "/rcm/insurance-ar-analysis": "Insurance AR Analysis",
};

/** Settings page link href to module name (for filtering which cards/links to show). */
export const SETTINGS_HREF_TO_MODULE_NAME: Record<string, string> = {
  "/settings/organization": "Organizations",
  "/settings/users": "Users",
  "/settings/roles-permissions": "Roles",
  "/settings/security-access": "Security Access",
  "/settings/entities": "Entities",
  "/settings/entity-locations": "Entity Locations",
  "/settings/entity-providers": "Entity Providers",
  "/settings/entity-fee-schedules": "Entity Fee Schedules",
  "/settings/payers": "Payers",
  "/settings/plans": "Plans",
  "/settings/group-participation": "Group Provider Plan Participations",
  "/settings/rendering-participation": "Rendering Provider Plan Participations",
  "/settings/facilities": "Facilities",
  "/settings/fee-schedules": "Fee Schedules",
  "/settings/geography-resolution": "Zip Geo Mappings",
  "/settings/applicability-rules": "Applicability Rules",
  "/settings/icd-codes": "ICD Codes",
  "/settings/ndc-codes": "NDC Codes",
  "/settings/cpt-hcpcs-codes": "CPT/HCPCS Codes",
  "/settings/modifiers": "Modifiers",
  "/settings/financial-modifiers": "Financial Modifiers",
  "/settings/bundling-reduction-rules": "Bundling/Reduction Rules",
  "/settings/procedure-grouping-rules": "Procedure Grouping Rules",
  "/settings/nsa-eligibility": "NSA Eligibility",
  "/settings/nsa-federal": "NSA Federal",
  "/settings/nsa-state": "NSA State",
  "/settings/nsa-emergency": "NSA Emergency",
};
